### ISSUE TITLE
Opret $ENV variabel med test-nøgle fra leverandør

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/vis-statistik-virtuel-hjemmesygepleje#1]
```[tasklist]
### Tasks
- [ ] Kontakt imellem KIT og leverandør etableres @tna-randers
- [ ] Adgangsgivende information (user/pass) modtages af KIT fra Leverandør @orehoj
- [x] $VIEWCARE_SFTP_USER og @VIEWCARE_SFTP_PASS oprettes som github secrets og udfyldes med info
- [x] Github secrets mappes til $ENV variable i docker-compose fil så de kan anvendes til udvikling @jmk-randers
- [ ] ENV variable oprettes i prototypes og i produktions miljøerne @orehoj
```
