### ISSUE TITLE
Visualisering af statistik for virtuel hjemmesygepleje (85.11.00-P20-19-23)

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/vis-statistik-virtuel-hjemmesygepleje#2]
### En standard datapipeline (ETL) på platformen kan anvendes og det vil kunne visualiseres i enten et eksisterende modul som SuperSet eller et andet modul hvis de kan afsætte midler til det.

```[tasklist]
### Tasks
- [x] Kontakt leverandør og meld klar til at modtage .CSV filer @tna-randers
- [ ] https://github.com/Randers-Kommune-Digitalisering/vis-statistik-virtuel-hjemmesygepleje/pull/3
- [x] Vurder om https://github.com/joeartsea/node-red-contrib-ftp kan bruges som SFTP node
- [ ] Risikovurdering
- [ ] Data analyse og kolonne beskrivelse fra ViewCare
- [x] Forventningsafstemning på hvad der skal visualiseres
- [ ] https://github.com/Randers-Kommune-Digitalisering/vis-statistik-virtuel-hjemmesygepleje/issues/7
- [ ] https://github.com/Randers-Kommune-Digitalisering/vis-statistik-virtuel-hjemmesygepleje/issues/6
- [ ] https://github.com/Randers-Kommune-Digitalisering/vis-statistik-virtuel-hjemmesygepleje/issues/10
- [x] User stories / behovsafklaring
- [ ] Digitalisering indkalder til statusmøde når prototype er klar
- [ ] Dataafleveringsmodul
```

Der skal laves en arbejdsgruppe til projektet.

Der skal vurderes om der skal laves databehandleraftale og risikovurdering

Og inden det går i drift i v.1.0. skal der være fundet en systemejer og et par systemforvaltere der kan håndtere overvågning, adgangsstyring m.v.

----------------------------

Mail til velfærds sekretariatet der har initieret en projektopstart:

_```
Fra: René Demant Juncher <[Rene.Demant.Juncher@randers.dk](mailto:Rene.Demant.Juncher@randers.dk)>
Sendt: 12. april 2023 10:40
Til: Iben Fog Thomsen <[ift@viewcare.com](mailto:ift@viewcare.com)>
Cc: Olaf Grønvaldt <[ogr@viewcare.com](mailto:ogr@viewcare.com)>; Tom Nørregaard Andersen <[Tom.Norregaard.Andersen@randers.dk](mailto:Tom.Norregaard.Andersen@randers.dk)>; Helle Kirkemand Bendtsen <[Helle.Kirkemand.Bendtsen@randers.dk](mailto:Helle.Kirkemand.Bendtsen@randers.dk)>
Emne: SV: Dataoverførsel

 

Hej Iben

 

Så har vi drøftet opgaven med Louise og Camilla, og vi er enige om at vi gerne vil arbejde videre med at få et bedre interface, specifikt ift. det vi har set med applikator.

Derudover vil vi rigtig gerne have de historiske data med ind fra  jer.  -  Olaf har efterspurgt at få en direkte kontakt, og det kan han få gennem Tom. 

Vi har allerede gjort os nogle tanker om hvordan vi kunne ønske os det, :  - og som jeg tolker det,  vil vi gerne ”Pull” data.  -  - første gang hele molevitten, efterfølgende kun ændringerne.  Når den sidste skræm er pillet ned, lægger vi data et sted hos os selv, og i kan slette dem.
```_
